# Generated by Django 2.0.6 on 2018-06-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('decrypted_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('encrypted_text', models.CharField(max_length=200)),
            ],
        ),
    ]
